pool:
  name: QA-MacOS
steps:
- script: |
   npm install -g artillery
   
  displayName: 'Install Artillery'

- script: |
   npm install -g fs
   
  displayName: 'Install fs'

- script: |
   set DEBUG=http:capture
   artillery run -e staging -o artillery_results test.yml
  displayName: 'Run Tests'

- script: |	
    artillery report artillery_results	
    exit
  displayName: 'Convert report'
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: artillery_results
  enabled: true

