pool:
  name: QA-PC
steps:
- script: |
   npm install -g artillery
   
  displayName: 'Install Artillery'

- script: |
   set DEBUG=http:response
   artillery run -e staging -o artillery_results test.yml > log.txt
  displayName: 'Run Tests'

- script: |
    artillery report artillery_results

  displayName: 'Convert report'
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: artillery_results
  enabled: true

