pool:
  name: QA-PC
steps:
- script: |
   npm install -g artillery
   
  displayName: 'Install Artillery'

- script: |
   artillery run -e staging -o report.json test.yml
   
  displayName: 'Run Tests'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: report.json
  enabled: true


