pool:
  name: QA-PC
steps:
- script: |
   npm install -g artillery
   
  displayName: 'Install Artillery'

- script: |
   artillery run -e staging -o report.json test.yml
  failOnStderr: true 
  displayName: 'Run Tests'

- script: |
    artillery report report.json

  displayName: 'Convert report'
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: report.json
  enabled: true

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'd0a0b220-4a56-4bb1-aa8d-4ad1b15d371f'
    definition: '289'
    buildVersionToDownload: 'specific'
    pipelineId: '23257'
    artifactName: 'report.json'
    targetPath: '$(Pipeline.Workspace)'
