# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: Hosted
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g newman'

- task: carlowahlstedt.NewmanPostman.NewmanPostman.NewmanPostman@4
  displayName: 'Newman - Postman'
  inputs:
    collectionFileSource: 'App_API_Automation.json'
    environment: 'Staging.postman_environment.json'
    ignoreRedirect: false
    bail: false
    sslInsecure: false
    reporters: junit
    htmlExtraDarkTheme: false
    htmlExtraLogs: false
    htmlExtraTestPaging: false
    reporterJUnitExport: postmanResults.xml
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/postmanResults.xml'
  inputs:
    testResultsFiles: '**/postmanResults.xml'

